//! # Provenance Chain Validator
//!
//! Validates the integrity of the evidence provenance chain from raw artifact
//! through parsing to normalization. Every normalized record must trace back
//! to a specific parsed record, which must trace back to exact bytes in a
//! raw artifact. If any link in this chain is broken, the evidence may be
//! challenged in court.
//!
//! # Validation Rules
//!
//! 1. **Source Reference Completeness:** Every record must have a non-empty
//!    `artifact_id`, `artifact_hash`, `parser_id`, and `parser_version`.
//! 2. **Hash Consistency:** The `artifact_hash` in the source reference must
//!    match the hash of the actual artifact in the evidence store.
//! 3. **Temporal Ordering:** Parsing timestamps must be after acquisition
//!    timestamps, and normalization timestamps must be after parsing timestamps.
//! 4. **Layer Progression:** Records must progress Raw → Parsed → Normalized.
//!    A normalized record cannot reference raw layer directly (must go through parsed).
//! 5. **Parser Version Consistency:** All records from the same parser invocation
//!    must report the same parser version.
//!
//! # Forensic Significance
//!
//! The provenance chain is the backbone of evidence admissibility. Without it,
//! opposing counsel can argue that derived findings have no verifiable connection
//! to the original device data. Every court-ready report must include a provenance
//! chain attestation generated by this validator.

use chrono::{DateTime, Utc};
use oracle_core::types::{ArtifactId, EvidenceLayer, RecordId, SourceReference};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ──────────────────────────────────────────────────────────────────────────────
// Validation Types
// ──────────────────────────────────────────────────────────────────────────────

/// Unique identifier for a validation run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ValidationId(pub Uuid);

impl ValidationId {
    pub fn new() -> Self {
        ValidationId(Uuid::new_v4())
    }
}

impl Default for ValidationId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ValidationId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The result of a single provenance chain validation check.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValidationResult {
    /// The check passed.
    Pass,
    /// The check failed with a reason.
    Fail(String),
    /// The check could not be performed (missing data).
    Skipped(String),
}

impl ValidationResult {
    pub fn is_pass(&self) -> bool {
        matches!(self, ValidationResult::Pass)
    }

    pub fn is_fail(&self) -> bool {
        matches!(self, ValidationResult::Fail(_))
    }
}

impl std::fmt::Display for ValidationResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ValidationResult::Pass => write!(f, "PASS"),
            ValidationResult::Fail(reason) => write!(f, "FAIL: {}", reason),
            ValidationResult::Skipped(reason) => write!(f, "SKIPPED: {}", reason),
        }
    }
}

/// A single provenance chain link being validated.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceLink {
    /// The record whose provenance is being validated.
    pub record_id: RecordId,
    /// The evidence layer of this record.
    pub layer: EvidenceLayer,
    /// The source reference claimed by this record.
    pub source_ref: SourceReference,
    /// Optional: the evidence layer of the parent record.
    pub parent_layer: Option<EvidenceLayer>,
}

/// A single validation finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationFinding {
    /// Which check produced this finding.
    pub check_name: String,
    /// The record being validated.
    pub record_id: RecordId,
    /// The artifact referenced by the record.
    pub artifact_id: ArtifactId,
    /// The result of the check.
    pub result: ValidationResult,
}

// ──────────────────────────────────────────────────────────────────────────────
// Validation Report
// ──────────────────────────────────────────────────────────────────────────────

/// Complete provenance chain validation report for an investigation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceReport {
    /// Unique identifier for this validation run.
    pub validation_id: ValidationId,
    /// All individual findings.
    pub findings: Vec<ValidationFinding>,
    /// Overall validation status.
    pub overall_result: ValidationResult,
    /// Summary statistics.
    pub summary: ProvenanceSummary,
    /// When this validation was performed.
    pub validated_at: DateTime<Utc>,
}

/// Summary statistics for a provenance validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceSummary {
    pub total_checks: usize,
    pub passed: usize,
    pub failed: usize,
    pub skipped: usize,
    pub records_validated: usize,
}

// ──────────────────────────────────────────────────────────────────────────────
// Provenance Chain Validator
// ──────────────────────────────────────────────────────────────────────────────

/// Validates the integrity of evidence provenance chains.
///
/// The validator receives provenance links and known artifact hashes,
/// then executes a series of checks to verify the chain is unbroken.
pub struct ProvenanceValidator {
    findings: Vec<ValidationFinding>,
    /// Known artifact hashes: artifact_id → sha256 hash from the evidence store.
    known_hashes: std::collections::HashMap<String, String>,
    /// Known artifact acquisition timestamps.
    acquisition_times: std::collections::HashMap<String, DateTime<Utc>>,
}

impl ProvenanceValidator {
    /// Create a new provenance validator.
    pub fn new() -> Self {
        ProvenanceValidator {
            findings: Vec::new(),
            known_hashes: std::collections::HashMap::new(),
            acquisition_times: std::collections::HashMap::new(),
        }
    }

    /// Register a known artifact hash from the evidence store.
    ///
    /// This is used to cross-reference source references against
    /// the actual stored artifact hashes.
    pub fn register_artifact_hash(&mut self, artifact_id: &ArtifactId, hash: &str) {
        self.known_hashes
            .insert(artifact_id.to_string(), hash.to_string());
    }

    /// Register a known artifact acquisition time.
    pub fn register_acquisition_time(
        &mut self,
        artifact_id: &ArtifactId,
        acquired_at: DateTime<Utc>,
    ) {
        self.acquisition_times
            .insert(artifact_id.to_string(), acquired_at);
    }

    /// Validate a single provenance link.
    ///
    /// This runs all applicable checks against the provided link:
    /// - Source reference completeness
    /// - Hash consistency (if known)
    /// - Temporal ordering (if acquisition time is known)
    /// - Layer progression
    pub fn validate_link(&mut self, link: &ProvenanceLink) {
        self.check_source_reference_completeness(link);
        self.check_hash_consistency(link);
        self.check_temporal_ordering(link);
        self.check_layer_progression(link);
    }

    /// Generate the final provenance validation report.
    pub fn generate_report(self) -> ProvenanceReport {
        let total = self.findings.len();
        let passed = self.findings.iter().filter(|f| f.result.is_pass()).count();
        let failed = self.findings.iter().filter(|f| f.result.is_fail()).count();
        let skipped = total - passed - failed;

        let records_validated: usize = {
            let mut seen = std::collections::HashSet::new();
            for f in &self.findings {
                seen.insert(f.record_id.0);
            }
            seen.len()
        };

        let overall = if failed > 0 {
            ValidationResult::Fail(format!("{} check(s) failed", failed))
        } else {
            ValidationResult::Pass
        };

        ProvenanceReport {
            validation_id: ValidationId::new(),
            findings: self.findings,
            overall_result: overall,
            summary: ProvenanceSummary {
                total_checks: total,
                passed,
                failed,
                skipped,
                records_validated,
            },
            validated_at: Utc::now(),
        }
    }

    /// Return a reference to all current findings.
    pub fn findings(&self) -> &[ValidationFinding] {
        &self.findings
    }

    // ── Individual Checks ───────────────────────────────────────────────

    /// Check 1: Source reference has all required fields populated.
    fn check_source_reference_completeness(&mut self, link: &ProvenanceLink) {
        let ref_complete = !link.source_ref.artifact_hash.is_empty()
            && !link.source_ref.parser_id.is_empty()
            && !link.source_ref.parser_version.is_empty();

        let result = if ref_complete {
            ValidationResult::Pass
        } else {
            let mut missing = Vec::new();
            if link.source_ref.artifact_hash.is_empty() {
                missing.push("artifact_hash");
            }
            if link.source_ref.parser_id.is_empty() {
                missing.push("parser_id");
            }
            if link.source_ref.parser_version.is_empty() {
                missing.push("parser_version");
            }
            ValidationResult::Fail(format!(
                "Source reference is incomplete — missing: {}",
                missing.join(", ")
            ))
        };

        self.findings.push(ValidationFinding {
            check_name: "source_reference_completeness".to_string(),
            record_id: link.record_id,
            artifact_id: link.source_ref.artifact_id,
            result,
        });
    }

    /// Check 2: Artifact hash in source reference matches the evidence store.
    fn check_hash_consistency(&mut self, link: &ProvenanceLink) {
        let artifact_key = link.source_ref.artifact_id.to_string();

        let result = match self.known_hashes.get(&artifact_key) {
            Some(stored_hash) => {
                if *stored_hash == link.source_ref.artifact_hash {
                    ValidationResult::Pass
                } else {
                    ValidationResult::Fail(format!(
                        "Hash mismatch: source reference claims {} but evidence store has {}",
                        &link.source_ref.artifact_hash[..16.min(link.source_ref.artifact_hash.len())],
                        &stored_hash[..16.min(stored_hash.len())]
                    ))
                }
            }
            None => ValidationResult::Skipped(format!(
                "Artifact {} not found in known hash registry",
                artifact_key
            )),
        };

        self.findings.push(ValidationFinding {
            check_name: "hash_consistency".to_string(),
            record_id: link.record_id,
            artifact_id: link.source_ref.artifact_id,
            result,
        });
    }

    /// Check 3: Parsing timestamp is after acquisition timestamp.
    fn check_temporal_ordering(&mut self, link: &ProvenanceLink) {
        let artifact_key = link.source_ref.artifact_id.to_string();

        let result = match self.acquisition_times.get(&artifact_key) {
            Some(acq_time) => {
                if link.source_ref.parsed_at >= *acq_time {
                    ValidationResult::Pass
                } else {
                    ValidationResult::Fail(format!(
                        "Parsing timestamp ({}) is before acquisition timestamp ({}). \
                         This violates temporal causality and suggests data corruption.",
                        link.source_ref.parsed_at.format("%Y-%m-%dT%H:%M:%SZ"),
                        acq_time.format("%Y-%m-%dT%H:%M:%SZ")
                    ))
                }
            }
            None => ValidationResult::Skipped(format!(
                "Acquisition time for artifact {} not registered",
                artifact_key
            )),
        };

        self.findings.push(ValidationFinding {
            check_name: "temporal_ordering".to_string(),
            record_id: link.record_id,
            artifact_id: link.source_ref.artifact_id,
            result,
        });
    }

    /// Check 4: Evidence layer progression is valid.
    ///
    /// Valid progressions: Raw → Parsed, Parsed → Normalized, Normalized → Correlated.
    /// Invalid: skipping layers (e.g., Raw → Normalized) or backwards (Parsed → Raw).
    fn check_layer_progression(&mut self, link: &ProvenanceLink) {
        let result = match link.parent_layer {
            Some(parent) => {
                if Self::is_valid_progression(parent, link.layer) {
                    ValidationResult::Pass
                } else {
                    ValidationResult::Fail(format!(
                        "Invalid layer progression: {:?} → {:?}. \
                         Records must progress Raw → Parsed → Normalized → Correlated.",
                        parent, link.layer
                    ))
                }
            }
            None => {
                // No parent layer — valid only if this is Raw or Parsed (initial ingestion)
                if link.layer == EvidenceLayer::Raw || link.layer == EvidenceLayer::Parsed {
                    ValidationResult::Pass
                } else {
                    ValidationResult::Fail(format!(
                        "Record at layer {:?} has no parent layer reference. \
                         Only Raw and Parsed layers may lack a parent.",
                        link.layer
                    ))
                }
            }
        };

        self.findings.push(ValidationFinding {
            check_name: "layer_progression".to_string(),
            record_id: link.record_id,
            artifact_id: link.source_ref.artifact_id,
            result,
        });
    }

    /// Determine if a layer progression is valid.
    fn is_valid_progression(from: EvidenceLayer, to: EvidenceLayer) -> bool {
        matches!(
            (from, to),
            (EvidenceLayer::Raw, EvidenceLayer::Parsed)
                | (EvidenceLayer::Parsed, EvidenceLayer::Normalized)
                | (EvidenceLayer::Normalized, EvidenceLayer::Correlated)
        )
    }
}

impl Default for ProvenanceValidator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use oracle_core::types::{ArtifactId, RecordId};

    fn make_source_ref(hash: &str, parser: &str, version: &str) -> SourceReference {
        SourceReference {
            artifact_id: ArtifactId::new(),
            artifact_hash: hash.to_string(),
            parser_id: parser.to_string(),
            parser_version: version.to_string(),
            byte_offset: Some(0),
            byte_length: Some(1024),
            db_row_id: None,
            parsed_at: Utc::now(),
        }
    }

    fn make_link(
        layer: EvidenceLayer,
        parent: Option<EvidenceLayer>,
        source_ref: SourceReference,
    ) -> ProvenanceLink {
        ProvenanceLink {
            record_id: RecordId::new(),
            layer,
            source_ref,
            parent_layer: parent,
        }
    }

    // ── Completeness Tests ──────────────────────────────────────────────

    #[test]
    fn test_complete_source_reference_passes() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("abc123", "wpa_parser", "1.0.0");
        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);

        validator.validate_link(&link);

        let completeness = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "source_reference_completeness")
            .unwrap();
        assert!(completeness.result.is_pass());
    }

    #[test]
    fn test_missing_hash_fails_completeness() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("", "wpa_parser", "1.0.0");
        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);

        validator.validate_link(&link);

        let completeness = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "source_reference_completeness")
            .unwrap();
        assert!(completeness.result.is_fail());
    }

    #[test]
    fn test_missing_parser_id_fails_completeness() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("abc123", "", "1.0.0");
        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);

        validator.validate_link(&link);

        let completeness = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "source_reference_completeness")
            .unwrap();
        assert!(completeness.result.is_fail());
    }

    // ── Hash Consistency Tests ──────────────────────────────────────────

    #[test]
    fn test_hash_matches_passes() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("deadbeef01234567", "parser", "1.0");
        let artifact_id = src.artifact_id;
        validator.register_artifact_hash(&artifact_id, "deadbeef01234567");

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let hash_check = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "hash_consistency")
            .unwrap();
        assert!(hash_check.result.is_pass());
    }

    #[test]
    fn test_hash_mismatch_fails() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("deadbeef01234567", "parser", "1.0");
        let artifact_id = src.artifact_id;
        validator.register_artifact_hash(&artifact_id, "cafebabe89abcdef");

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let hash_check = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "hash_consistency")
            .unwrap();
        assert!(hash_check.result.is_fail());
    }

    #[test]
    fn test_unknown_artifact_skipped() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("deadbeef01234567", "parser", "1.0");
        // Don't register any hash

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let hash_check = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "hash_consistency")
            .unwrap();
        assert!(matches!(hash_check.result, ValidationResult::Skipped(_)));
    }

    // ── Temporal Ordering Tests ─────────────────────────────────────────

    #[test]
    fn test_parsing_after_acquisition_passes() {
        let mut validator = ProvenanceValidator::new();
        let acq_time = Utc::now() - chrono::Duration::hours(1);
        let mut src = make_source_ref("hash", "parser", "1.0");
        src.parsed_at = Utc::now();
        let artifact_id = src.artifact_id;
        validator.register_acquisition_time(&artifact_id, acq_time);

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let temporal = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "temporal_ordering")
            .unwrap();
        assert!(temporal.result.is_pass());
    }

    #[test]
    fn test_parsing_before_acquisition_fails() {
        let mut validator = ProvenanceValidator::new();
        let acq_time = Utc::now();
        let mut src = make_source_ref("hash", "parser", "1.0");
        src.parsed_at = acq_time - chrono::Duration::hours(1); // Before acquisition!
        let artifact_id = src.artifact_id;
        validator.register_acquisition_time(&artifact_id, acq_time);

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let temporal = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "temporal_ordering")
            .unwrap();
        assert!(temporal.result.is_fail());
    }

    // ── Layer Progression Tests ─────────────────────────────────────────

    #[test]
    fn test_valid_raw_to_parsed() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "parser", "1.0");
        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_pass());
    }

    #[test]
    fn test_valid_parsed_to_normalized() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "normalizer", "1.0");
        let link = make_link(
            EvidenceLayer::Normalized,
            Some(EvidenceLayer::Parsed),
            src,
        );
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_pass());
    }

    #[test]
    fn test_invalid_skip_raw_to_normalized() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "normalizer", "1.0");
        let link = make_link(
            EvidenceLayer::Normalized,
            Some(EvidenceLayer::Raw), // Skipping parsed!
            src,
        );
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_fail());
    }

    #[test]
    fn test_invalid_backwards_parsed_to_raw() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "parser", "1.0");
        let link = make_link(
            EvidenceLayer::Raw,
            Some(EvidenceLayer::Parsed), // Backwards!
            src,
        );
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_fail());
    }

    #[test]
    fn test_no_parent_raw_layer_passes() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "ingestor", "1.0");
        let link = make_link(EvidenceLayer::Raw, None, src);
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_pass());
    }

    #[test]
    fn test_no_parent_normalized_layer_fails() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash", "normalizer", "1.0");
        let link = make_link(EvidenceLayer::Normalized, None, src);
        validator.validate_link(&link);

        let layer = validator
            .findings()
            .iter()
            .find(|f| f.check_name == "layer_progression")
            .unwrap();
        assert!(layer.result.is_fail());
    }

    // ── Report Generation Tests ─────────────────────────────────────────

    #[test]
    fn test_all_passing_report() {
        let mut validator = ProvenanceValidator::new();
        let src = make_source_ref("hash123", "wpa_parser", "1.0.0");
        let artifact_id = src.artifact_id;
        validator.register_artifact_hash(&artifact_id, "hash123");
        validator.register_acquisition_time(
            &artifact_id,
            Utc::now() - chrono::Duration::hours(1),
        );

        let link = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src);
        validator.validate_link(&link);

        let report = validator.generate_report();
        assert!(report.overall_result.is_pass());
        assert_eq!(report.summary.failed, 0);
        assert_eq!(report.summary.records_validated, 1);
    }

    #[test]
    fn test_mixed_report() {
        let mut validator = ProvenanceValidator::new();

        // Good link
        let src1 = make_source_ref("hash_ok", "parser", "1.0");
        let aid1 = src1.artifact_id;
        validator.register_artifact_hash(&aid1, "hash_ok");
        let link1 = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src1);
        validator.validate_link(&link1);

        // Bad link: empty hash
        let src2 = make_source_ref("", "parser", "1.0");
        let link2 = make_link(EvidenceLayer::Parsed, Some(EvidenceLayer::Raw), src2);
        validator.validate_link(&link2);

        let report = validator.generate_report();
        assert!(report.overall_result.is_fail());
        assert!(report.summary.failed > 0);
        assert_eq!(report.summary.records_validated, 2);
    }
}
